language: generic
sudo: required
services:
  - docker

before_script:
  - docker build -t taraspyzo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true taraspyzo/docker-react npm run test -- --coverage
